#!/bin/sh

cp .git/hooks/pre-commit English/backend/pre-commit
wait $!
npm run --prefix English/ build
wait $!
node English/backend/save_pdf.js
wait $!

git add English/dist/main.bundle.js
git add English/LukaZivanovic_CV.pdf
git add English/backend/pre-commit

exit 0
